import './globals.css'; // Projenin global stil dosyasını içe aktarıyor
import type { Metadata } from 'next'; // Next.js'in Metadata türünü içe aktarıyor
import { Inter } from 'next/font/google'; // Google'dan "Inter" yazı tipini içe aktarıyor

// -----------------------------------------------------------------------------
// 1) Font ve Metadata Ayarları
// -----------------------------------------------------------------------------

// Google Fonts'tan "Inter" yazı tipini projemize dahil ediyoruz
const inter = Inter({ subsets: ['latin'] });

// Sayfa meta bilgileri, tarayıcı sekmesi ve SEO için önemlidir
export const metadata: Metadata = {
    title: 'Create Next App', // Sayfa başlığı
    description: 'Generated by create next app', // Sayfa açıklaması
};

// -----------------------------------------------------------------------------
// 2) RootLayout Bileşeni
// -----------------------------------------------------------------------------

/**
 * RootLayout bileşeni, tüm uygulamanın ortak düzenini belirler.
 * Tüm sayfalar ve bileşenler bu düzenin içine yerleştirilir.
 */
export default function RootLayout({
                                       children, // Alt bileşenlerin yerleştirileceği prop
                                   }: {
    children: React.ReactNode; // "React.ReactNode", herhangi bir React bileşenini temsil eder
}) {
    return (
        <html lang="en"> {/* HTML dilini İngilizce olarak ayarlıyor */}
        <body className={inter.className}> {/* Body'ye "Inter" fontunu uyguluyor */}
        {children} {/* Bu, diğer bileşenlerin buraya yerleştirileceği yerdir */}
        </body>
        </html>
    );
}
